### ISSUE TITLE
stripe.cfc - getToken function name causes CF error

### ISSUE THREAD

**Issue by MiY4MOTO** [ghidinelli/cfpayment#22]
If I implement the example exactly "as is" on Coldfusion 8, I get the following CF error;

The names of user-defined functions cannot be the same as built-in ColdFusion functions.
The name getToken is the name of a built-in ColdFusion function.
The CFML compiler was processing:

A cffunction tag beginning on line 216, column 10.
 
The error occurred in C:\inetpub\wwwroot\cfpayment\api\gateway\stripe\stripe.cfc: line 216
Called from C:\inetpub\wwwroot\cfpayment\api\core.cfc: line 52

**Comment by ghidinelli** [comment]
Thanks for the report...  when you say the example as is, are you referring to the 6-liner in the README? 

getToken() is part of recent work on the stripe gateway.  If you temporarily use this commit:  

https://github.com/ghidinelli/cfpayment/commit/95a13b489b48b2833287059c151571111764be7d#diff-1bc979c4da2f112dd72a5535e4925476

You should be OK and I'll make sure this is corrected as part of some more work I'm doing.

**Comment by MiY4MOTO** [comment]
Thanks for that.

Yes, I was referring to the example in the README. Basically, as soon as you reference the stripe.cfc the error is thrown.

The issue doesn't occur on CF11, so it may well only affect CF8. I don't have 9 or 10 available to me so I can't check if they exhibit the same behaviour.

**Comment by ghidinelli** [comment]
Yeah, doesn't occur in CF10 for me either I don't think.

**Comment by ghidinelli** [comment]
Odd that it doesn't throw an error in CF10 or 11, but for safety, I renamed to getAccountToken()
