### ISSUE TITLE
the trustAnchors parameter must be non-empty

### ISSUE THREAD

**Issue by JamoCA** [ghidinelli/cfpayment#28]
In early Feb 2016, We updated to the latest Windows 2012 updates and CFPayment quit working (it's actually more of an Adobe bug).  We use ColdFusion 10,0,17,295085 (Java 1.8.0_66) and the latest CFPayments + Stripe and started getting this error:

    I/O Exception: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

getSuccess() is false.  getStatusCode() returns "99" (This status indicates an exception we don't know how to handle (yet)), but getMessage() returns an empty string... no message.  So the customer (and developer) don't have any idea regarding what happened.

My personal workaround for this is going to be to rewrite base.cfc to use CFX_HTTP5 so that it will continue to work regardless of the version of ColdFusion or third-party SSL Certificate used.  Let me know if you are interested and I can provide you with the modified template.

**Comment by ghidinelli** [comment]
James - can you tell me specifically what problem you're running into? I'm on CF10 with Stripe and don't have any problems. AFAIK, cfpayment works on Railo and cfx_http5 would break that (not to mention Linux compatibility) so it probably won't work as a general solution.

**Comment by JamoCA** [comment]
The `doHttpCall` function was failing with the above posted error message.  It worked, but then after installing a recent Windows patches (and not changing any CF settings or code), it started throwing the above error.  We didn't encounter this issue on other CF10 servers.  I modified the script to work with CFX_HTTP5 and it has been working well.

Even if this modification wouldn't be compatible w/Railo or Linux, it could benefit CF9 servers as some of the gateway providers move to TLS1.2 (which doesn't work w/CF9.).

**Comment by JamoCA** [comment]
I think Windows update JRE to 1.8.0_71.  Some ciphers are disabled and CFHTTP may be dependent on them.

**Comment by ghidinelli** [comment]
No JRE would definitely be a problem. ;)  Glad to hear it's working again!  We just updated to _72 a few days back and it's working well on CF10.
