### ISSUE TITLE
Stripe upgrades

### ISSUE THREAD

**Issue by Junglefish** [ghidinelli/cfpayment#36]
Hi
Stripe recently upgraded their APIs to be SCA-Ready. I see that the last code commit for CFPayment was December-2017, so does that mean that the code as it stands will not work with the new Stripe API?

**Comment by ghidinelli** [comment]
Hi @Junglefish - it's correct that cfpayment is not SCA-ready. We recently made the decision to reimplement our payment processing in javascript/node and will be using the Stripe-provided JS libraries so I will not be upgrading cfpayment. Someone else could definitely take on the work. It's not trivial for many flows unfortunately.
